set( agg_INCLUDE agg-2.4/include )
set( agg_SRC agg-2.4/src )
set( agg_HEADERS
	${agg_INCLUDE}/agg_alpha_mask_u8.h
	${agg_INCLUDE}/agg_arc.h
	${agg_INCLUDE}/agg_array.h
	${agg_INCLUDE}/agg_arrowhead.h
	${agg_INCLUDE}/agg_basics.h
	${agg_INCLUDE}/agg_bezier_arc.h
	${agg_INCLUDE}/agg_bitset_iterator.h
	${agg_INCLUDE}/agg_blur.h
	${agg_INCLUDE}/agg_bounding_rect.h
	${agg_INCLUDE}/agg_bspline.h
	${agg_INCLUDE}/agg_clip_liang_barsky.h
	${agg_INCLUDE}/agg_color_conv.h
	${agg_INCLUDE}/agg_color_conv_rgb16.h
	${agg_INCLUDE}/agg_color_conv_rgb8.h
	${agg_INCLUDE}/agg_color_gray.h
	${agg_INCLUDE}/agg_color_rgba.h
	${agg_INCLUDE}/agg_config.h
	${agg_INCLUDE}/agg_conv_adaptor_vcgen.h
	${agg_INCLUDE}/agg_conv_adaptor_vpgen.h
	${agg_INCLUDE}/agg_conv_bspline.h
	${agg_INCLUDE}/agg_conv_clip_polygon.h
	${agg_INCLUDE}/agg_conv_clip_polyline.h
	${agg_INCLUDE}/agg_conv_close_polygon.h
	${agg_INCLUDE}/agg_conv_concat.h
	${agg_INCLUDE}/agg_conv_contour.h
	${agg_INCLUDE}/agg_conv_curve.h
	${agg_INCLUDE}/agg_conv_dash.h
	${agg_INCLUDE}/agg_conv_gpc.h
	${agg_INCLUDE}/agg_conv_marker_adaptor.h
	${agg_INCLUDE}/agg_conv_marker.h
	${agg_INCLUDE}/agg_conv_segmentator.h
	${agg_INCLUDE}/agg_conv_shorten_path.h
	${agg_INCLUDE}/agg_conv_smooth_poly1.h
	${agg_INCLUDE}/agg_conv_stroke.h
	${agg_INCLUDE}/agg_conv_transform.h
	${agg_INCLUDE}/agg_conv_unclose_polygon.h
	${agg_INCLUDE}/agg_curves.h
	${agg_INCLUDE}/agg_dda_line.h
	${agg_INCLUDE}/agg_ellipse_bresenham.h
	${agg_INCLUDE}/agg_ellipse.h
	${agg_INCLUDE}/agg_embedded_raster_fonts.h
	${agg_INCLUDE}/agg_font_cache_manager2.h
	${agg_INCLUDE}/agg_font_cache_manager.h
	${agg_INCLUDE}/agg_font_freetype2.h
	${agg_INCLUDE}/agg_font_freetype.h
	${agg_INCLUDE}/agg_gamma_functions.h
	${agg_INCLUDE}/agg_gamma_lut.h
	${agg_INCLUDE}/agg_glyph_raster_bin.h
	${agg_INCLUDE}/agg_gradient_lut.h
	${agg_INCLUDE}/agg_gsv_text.h
	${agg_INCLUDE}/agg_image_accessors.h
	${agg_INCLUDE}/agg_image_filters.h
	${agg_INCLUDE}/agg_line_aa_basics.h
	${agg_INCLUDE}/agg_math.h
	${agg_INCLUDE}/agg_math_stroke.h
	${agg_INCLUDE}/agg_path_length.h
	${agg_INCLUDE}/agg_path_storage.h
	${agg_INCLUDE}/agg_path_storage_integer.h
	${agg_INCLUDE}/agg_pattern_filters_rgba.h
	${agg_INCLUDE}/agg_pixfmt_amask_adaptor.h
	${agg_INCLUDE}/agg_pixfmt_base.h
	${agg_INCLUDE}/agg_pixfmt_gray.h
	${agg_INCLUDE}/agg_pixfmt_rgba.h
	${agg_INCLUDE}/agg_pixfmt_rgb.h
	${agg_INCLUDE}/agg_pixfmt_rgb_packed.h
	${agg_INCLUDE}/agg_pixfmt_transposer.h
	${agg_INCLUDE}/agg_rasterizer_cells_aa.h
	${agg_INCLUDE}/agg_rasterizer_compound_aa.h
	${agg_INCLUDE}/agg_rasterizer_outline_aa.h
	${agg_INCLUDE}/agg_rasterizer_outline.h
	${agg_INCLUDE}/agg_rasterizer_scanline_aa.h
	${agg_INCLUDE}/agg_rasterizer_scanline_aa_nogamma.h
	${agg_INCLUDE}/agg_rasterizer_sl_clip.h
	${agg_INCLUDE}/agg_renderer_base.h
	${agg_INCLUDE}/agg_renderer_markers.h
	${agg_INCLUDE}/agg_renderer_mclip.h
	${agg_INCLUDE}/agg_renderer_outline_aa.h
	${agg_INCLUDE}/agg_renderer_outline_image.h
	${agg_INCLUDE}/agg_renderer_primitives.h
	${agg_INCLUDE}/agg_renderer_raster_text.h
	${agg_INCLUDE}/agg_renderer_scanline.h
	${agg_INCLUDE}/agg_rendering_buffer_dynarow.h
	${agg_INCLUDE}/agg_rendering_buffer.h
	${agg_INCLUDE}/agg_rounded_rect.h
	${agg_INCLUDE}/agg_scanline_bin.h
	${agg_INCLUDE}/agg_scanline_boolean_algebra.h
	${agg_INCLUDE}/agg_scanline_p.h
	${agg_INCLUDE}/agg_scanline_storage_aa.h
	${agg_INCLUDE}/agg_scanline_storage_bin.h
	${agg_INCLUDE}/agg_scanline_u.h
	${agg_INCLUDE}/agg_shorten_path.h
	${agg_INCLUDE}/agg_simul_eq.h
	${agg_INCLUDE}/agg_span_allocator.h
	${agg_INCLUDE}/agg_span_converter.h
	${agg_INCLUDE}/agg_span_gouraud_gray.h
	${agg_INCLUDE}/agg_span_gouraud.h
	${agg_INCLUDE}/agg_span_gouraud_rgba.h
	${agg_INCLUDE}/agg_span_gradient_alpha.h
	${agg_INCLUDE}/agg_span_gradient_contour.h
	${agg_INCLUDE}/agg_span_gradient.h
	${agg_INCLUDE}/agg_span_gradient_image.h
	${agg_INCLUDE}/agg_span_image_filter_gray.h
	${agg_INCLUDE}/agg_span_image_filter.h
	${agg_INCLUDE}/agg_span_image_filter_rgba.h
	${agg_INCLUDE}/agg_span_image_filter_rgb.h
	${agg_INCLUDE}/agg_span_interpolator_adaptor.h
	${agg_INCLUDE}/agg_span_interpolator_linear.h
	${agg_INCLUDE}/agg_span_interpolator_persp.h
	${agg_INCLUDE}/agg_span_interpolator_trans.h
	${agg_INCLUDE}/agg_span_pattern_gray.h
	${agg_INCLUDE}/agg_span_pattern_rgba.h
	${agg_INCLUDE}/agg_span_pattern_rgb.h
	${agg_INCLUDE}/agg_span_solid.h
	${agg_INCLUDE}/agg_span_subdiv_adaptor.h
	${agg_INCLUDE}/agg_trans_affine.h
	${agg_INCLUDE}/agg_trans_bilinear.h
	${agg_INCLUDE}/agg_trans_double_path.h
	${agg_INCLUDE}/agg_trans_perspective.h
	${agg_INCLUDE}/agg_trans_single_path.h
	${agg_INCLUDE}/agg_trans_viewport.h
	${agg_INCLUDE}/agg_trans_warp_magnifier.h
	${agg_INCLUDE}/agg_vcgen_bspline.h
	${agg_INCLUDE}/agg_vcgen_contour.h
	${agg_INCLUDE}/agg_vcgen_dash.h
	${agg_INCLUDE}/agg_vcgen_markers_term.h
	${agg_INCLUDE}/agg_vcgen_smooth_poly1.h
	${agg_INCLUDE}/agg_vcgen_stroke.h
	${agg_INCLUDE}/agg_vcgen_vertex_sequence.h
	${agg_INCLUDE}/agg_vertex_sequence.h
	${agg_INCLUDE}/agg_vpgen_clip_polygon.h
	${agg_INCLUDE}/agg_vpgen_clip_polyline.h
	${agg_INCLUDE}/agg_vpgen_segmentator.h
)

set( agg_SOURCES
	${agg_SRC}/agg_arc.cpp
	${agg_SRC}/agg_arrowhead.cpp
	${agg_SRC}/agg_bezier_arc.cpp
	${agg_SRC}/agg_bspline.cpp
	${agg_SRC}/agg_color_rgba.cpp
	${agg_SRC}/agg_curves.cpp
	${agg_SRC}/agg_embedded_raster_fonts.cpp
	${agg_SRC}/agg_font_freetype2.cpp
	${agg_SRC}/agg_font_freetype.cpp
	${agg_SRC}/agg_gsv_text.cpp
	${agg_SRC}/agg_image_filters.cpp
	${agg_SRC}/agg_line_aa_basics.cpp
	${agg_SRC}/agg_line_profile_aa.cpp
	${agg_SRC}/agg_rounded_rect.cpp
	${agg_SRC}/agg_sqrt_tables.cpp
	${agg_SRC}/agg_trans_affine.cpp
	${agg_SRC}/agg_trans_double_path.cpp
	${agg_SRC}/agg_trans_single_path.cpp
	${agg_SRC}/agg_trans_warp_magnifier.cpp
	${agg_SRC}/agg_vcgen_bspline.cpp
	${agg_SRC}/agg_vcgen_contour.cpp
	${agg_SRC}/agg_vcgen_dash.cpp
	${agg_SRC}/agg_vcgen_markers_term.cpp
	${agg_SRC}/agg_vcgen_smooth_poly1.cpp
	${agg_SRC}/agg_vcgen_stroke.cpp
	${agg_SRC}/agg_vpgen_clip_polygon.cpp
	${agg_SRC}/agg_vpgen_clip_polyline.cpp
	${agg_SRC}/agg_vpgen_segmentator.cpp
)

include_directories(
	/usr/include/freetype2
)

add_library( agg STATIC
	${agg_SOURCES}
	${agg_HEADERS}
)

target_link_libraries( agg
	freetype
)
